# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bookify.api:
    build:
      context: "C:\\Users\\ShaneMonck\\Documents\\repos\\prac\\Pragmatic-Clean-Architecture"
      dockerfile: "Bookify.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\ShaneMonck\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\ShaneMonck\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "bookifyapi:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\ShaneMonck\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\ShaneMonck\\Documents\\repos\\prac\\Pragmatic-Clean-Architecture\\\
      Bookify.Api:/app:rw"
    - "C:\\Users\\ShaneMonck\\Documents\\repos\\prac\\Pragmatic-Clean-Architecture:/src:rw"
    - "C:\\Users\\ShaneMonck\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2022.3.2/bin:/riderLogsConf"
    - "C:\\Users\\ShaneMonck\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_26_15_51_14:/riderLogs:rw"
    working_dir: "/app"
